server:
  port: 9090
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fengpan0403/spring-cloud-config.git     # 配置git仓库的地址
          search-paths: /                         # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: fengpan0403@163.com           # git仓库的账号
          password: 0123456789a                   # git仓库的密码